---
title: "Exercise #3"
subtitle: "Fortgeschrittene Statistische Software für NF - SS 2024"
date: "`r Sys.Date()`"
author: "Pat Callahan (Matrikelnummer: 12672775)"
output:
  bookdown::html_document2:
    base_format: distill::distill_article
    toc: true
    toc_depth: 3
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=TRUE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      options(dplyr.print_max = 5),
                      fig.pos = "H", out.extra = "",
                      results = "hold")
library(dplyr)
library(lubridate)
library(magrittr)
library(ggplot2)
theme_set(theme_bw())
library(devtools)
library(reticulate)
# use_python('/usr/local/bin/python3.11-intel64')
```

## Exercise 1: Initializing git (4 Points)

For this whole exercise sheet we will be tracking all our changes to it
in git.

### Start by initializing a new R project with git support, called `2024-exeRcise-sheet-3`. If you forgot how to do this, you can follow this [guide](https://malikaihle.github.io/Introduction-RStudio-Git-GitHub/rstudio_project.html).

Per my email exchange with Jan, I was already tracking my work for this class in git. I have placed all of my work for this assignment in a separate branch, `exeRcise-sheet-3`. Files not pertaining to this assignment have been deleted from the branch for clarity.

### Commit the files generated by Rstudio.

Done.

### For all of the following tasks in this exercise sheet we ask you to always commit your changes after finishing each subtask e.g. create a commit after task *1d*, *1e* etc.

> Note: This applies only to answers that have text or code as their
> answer. If you complete tasks in a different order or forget to commit
> one, this is no problem. If you change your answers you can just
> create multiple commits to track the changes.

### Name 2 strengths and 2 weaknesses of git. (Don't forget to create a commit after this answer, see *1c*)

Strengths:

* Git scales well to large projects; very fast at logging changes in numerous, complex files.
* Git is currently, and for the last decade+ has been, the most popular version control system. This leads to a robust ecosystem of Q&A and help, and it's a transferable skill.
* Requires users to explicitly declare what and when they want to save files; a commit should be an intelligible unit of work. (This is a pro and con).


Weaknesses:

* Git has a steep learning curve, particularly for less technical people and teams.
* Many of the commands are "overloaded" meaning certain commands are responsible for a surprisingly large number of activities just based on different flags or options being provided.
* Project histories *can* be deleted/overwritten by mistake or on purpose (git is not a security or a true logging system).
* Can really only function effectively with text files.


### Knit this exercise sheet. Some new files will automatically be generated when knitting the sheet e.g. the HTML page. Ignore these files, as we only want to track the source files themselves.

My .gitignore has already been set to ignore many of these files:

```bash
.Rproj.user
.Rhistory
.RData
.Ruserdata
**.html
**.pdf
**_cache
**_files
```

## Exercise 2: Putting your Repository on GitHub (3.5 Points)

For this task you will upload your solution to GitHub.

### Create a new repository on GitHub in your account named `exeRcise-sheet-3`. Make sure you create a **public repository** so we are able to see it for grading. Add the link to the repository below:

### Push your code to this new repository by copying and executing the snippet on github listed under `…or push an existing repository from the command line`.

### Regularly push your latest changes to GitHub again and especially do
    so when you are finished with this sheet.

## Exercise 3: Baby-Names in Munich (3.5 Points)

Download the latest open datasets on given names ("Vornamen") from the
open data repository of the city of Munich for the years `2023` and
`2022`.

Link: <https://opendata.muenchen.de/dataset/vornamen-von-neugeborenen>

### Download the data for both years and track it in git. For small datasets like these adding them to git is not a problem.

### Load the data for both years into R. Check the type of the count variable ("Anzahl") and look into the data to determine why it is not numeric? Fix the problem in an appropriate manner, it is OK if some of the counts are inaccurate because of this. Explain your solution and the repercussions.

### Calculate the total number of babies born in Munich in 2022 and 2023. Which year had the bigger baby-boom?

### Add a new column `year` to both datasets which holds the correct year for each.

### Combine both datasets into one using `bind_rows()`.

### Combine the counts for same names to determine the most popular names across both years. Print out the top 10 names in a nicely formatted table for both years. Include a table caption.

## Exercise 4: Open Analysis (4 points)

This exercise is a bit more open-ended. You can choose any dataset from
[Our World in Data](https://ourworldindata.org/) and analyze it, while
determining the research question yourself.

### Go to <https://github.com/owid/owid-datasets/tree/master/datasets> and choose a dataset that interests you. You can have a look at <https://ourworldindata.org/> to gather some inspiration.

### Download the dataset and track it in git.

### Put the name / title of the dataset and a link to it below.

-   Dataset Name: ...
-   Link: <https://github.com/owid/owid-datasets/>...

### Come up with a (research) question you want to answer with the data and briefly explain why you believe this is an interesting question within one sentence. It should be a question that can be answered with the dataset and using R.

### Use R to answer your chosen question.

### Create a meaningful plot / figure with the dataset. Make sure to provide a figure caption (via the chunk options / Rmarkdown) and correctly label the figure.

## Final Note

Make sure to push all your commits and changes to GitHub before
submitting the exercise sheet.
